### ISSUE TITLE
Local check

### ISSUE THREAD

**Issue by Madis0** [fantahund/ChatLagRemover#1]
How about, instead of removing the feature altogether, the mod downloaded the friends list UUIDs and did the check locally instead? Would that be a feasible alternative?

**Comment by fantahund** [comment]
I find this block function completely unnecessary, so I have deactivated it completely. And downloading the UUIDs of friends doesn't help much either, because you can also block players you are not friends with. And then it would lead to jerks again if necessary. ^^

**Comment by Madis0** [comment]
I actually meant "block list", not "friend list", but fair enough if you're not interested either way.

**Comment by fantahund** [comment]
If you want to continue using the block function you can use this mod, which removes the laggs but the function remains.
[https://www.curseforge.com/minecraft/mc-mods/nochatlag](https://www.curseforge.com/minecraft/mc-mods/nochatlag)
